### ISSUE TITLE
Websocket Blocks after terminating without unsubscribing

### ISSUE THREAD

**Issue by samuel-tay** [crypto-org-chain/cronos-mainnet#1]
As discussed on Discord https://discord.com/channels/783264383978569728/783264902613565450/907267013028749322

It was discovered that subscribing to WS works. 

However, if a subscription is not unsubscribed and the session is terminated, then the WS blocks up and no further requests will be entertained. It doesn't help to reconnect and unsubscribe.

Also, in the instance where 2 clients are connected and if Client A terminates the session without unsubscribing, Client B blocks as well, and the whole WS blocks.

**Comment by samuel-tay** [comment]
https://github.com/crypto-org-chain/cronos/issues/207

**Comment by xfwil** [comment]
I had same with this issue too, i hope this can fix fastly. Because some project using ws for using ws "features" .
